import { createHash } from "node:crypto";
import type { APIRoute } from "astro";
import { AGENT_SKILLS, skillBody, skillUrl } from "../../../lib/agent-skills";
import { abs } from "../../../lib/agent-discovery";
import { getCatalog } from "../../../lib/catalog";

/**
 * /.well-known/agent-skills/index.json -- Agent Skills Discovery RFC v0.2.0.
 *
 * The digest is the reason this route renders the skill bodies rather than
 * describing them. An index is a promise that the bytes at `url` hash to
 * `digest`; the only way to keep that promise across a price change is to hash
 * the same string the SKILL.md route will serve, generated by the same
 * function, in the same build. Hand-maintained hashes go stale on the first
 * edit and then quietly fail verification for everyone.
 *
 * `node:crypto` is fine here: this is a static build, and the route runs in
 * Node at build time. Nothing in `agent-skills.ts` itself imports it, so the
 * Cloudflare Function that shares that module stays portable.
 */
export const GET: APIRoute = async () => {
  const catalog = await getCatalog();

  const body = {
    $schema: "https://schemas.agentskills.io/discovery/0.2.0/schema.json",
    skills: AGENT_SKILLS.map((skill) => ({
      name: skill.name,
      type: "skill-md" as const,
      description: skill.description,
      url: abs(skillUrl(skill.name)),
      digest:
        "sha256:" +
        createHash("sha256").update(skillBody(skill, catalog), "utf8").digest("hex"),
    })),
  };

  return new Response(JSON.stringify(body, null, 2), {
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
    },
  });
};
